#!/usr/bin/env bash

function main {
  local shome="${_sinopia_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  nodeenv --prebuilt --node=4.4.7 "$shome/vendor/nodeenv"
  source "$shome/vendor/nodeenv/bin/activate"
  block compile npm --registry https://registry.npmjs.org/

  mkdir -p "$shome/bin"
  ln -nfs "../node_modules/.bin/sinopia" "$shome/bin/"
}

main "$@"


