#!/usr/bin/env bash

function main {
  local shome="${_sinopia_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  cd "$shome"
  exec sinopia -l "0.0.0.0:4873"
}

main "$@"


